sudo: required
language: go

go:
  - 1.11.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - make test

after_success:
  - if [ -z "$QUAY_USER" ]; then
    echo "PR build, skipping Quay push";
    else
    echo $QUAY_PASS | docker login -u $QUAY_USER --password-stdin quay.io;

    DOCKER_TAG=${TRAVIS_BRANCH}-$(echo ${TRAVIS_COMMIT} | head -c7);
    docker build -t quay.io/${QUAY_REPOSITORY}:${DOCKER_TAG} -f Dockerfile.ci . ;

    echo "Pushing to quay.io/${QUAY_REPOSITORY}:${DOCKER_TAG}";
    docker push quay.io/${QUAY_REPOSITORY}:${DOCKER_TAG};

    echo "Pushing to quay.io/${QUAY_REPOSITORY}:${TRAVIS_BRANCH}";
    docker tag quay.io/${QUAY_REPOSITORY}:${DOCKER_TAG} quay.io/${QUAY_REPOSITORY}:${TRAVIS_BRANCH};
    docker push quay.io/${QUAY_REPOSITORY}:${TRAVIS_BRANCH};
    fi
